apiVersion: "storage.k8s.io/v1"
kind: "StorageClass"
metadata:
  name: "connect-ebs-sc"
  namespace: "connect"
  annotations:
    "storageclass.kubernetes.io/is-default-class": "true"
provisioner: "ebs.csi.aws.com"
reclaimPolicy: "Retain"
allowVolumeExpansion: true
volumeBindingMode: "WaitForFirstConsumer"
allowedTopologies:
  - matchLabelExpressions:
      - key: "topology.ebs.csi.aws.com/zone"
        values:
          - "${AWS_REGION}a"
          - "${AWS_REGION}b"
      - key: "topology.kubernetes.io/zone"
        values:
          - "${AWS_REGION}a"
          - "${AWS_REGION}b"
parameters:
  encrypted: "true"
  type: "gp3"
