apiVersion: v1
kind: ServiceAccount
metadata:
  name: ping-pong-server
  labels:
    app: ping-pong-server
    mode: cofide
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong-server
      mode: cofide
  template:
    metadata:
      labels:
        app: ping-pong-server
        mode: cofide
      annotations:
        "spiffe.cofide.io/enabled": "true"
        "spiffe.cofide.io/debug": "true"
    spec:
      serviceAccountName: ping-pong-server
      containers:
      - name: ping-pong-server
        image: ghcr.io/cofide/cofide-demos/ping-pong-cofide-server:${IMAGE_TAG}
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "100m"
        ports:
        - containerPort: 8443
        volumeMounts:
            - name: spiffe-workload-api
              mountPath: /spiffe-workload-api
              readOnly: true
        env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: unix:///spiffe-workload-api/spire-agent.sock
        - name: INSECURE_PORT
          value: ":8081"
      volumes:
      - name: spiffe-workload-api
        csi:
          driver: "csi.spiffe.io"
          readOnly: true
---

apiVersion: v1
kind: Service
metadata:
  name: ping-pong-server
spec:
  selector:
    app: ping-pong-server
    mode: cofide
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
      name: https-passthrough
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
  type: LoadBalancer
