apiVersion: v1
kind: Namespace
metadata:
  name: spire-server
  labels:
    name: spire-server
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: spire
    meta.helm.sh/release-namespace: spire-mgmt

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spire-server
  namespace: spire-server
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: spire
    meta.helm.sh/release-namespace: spire-mgmt

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-manager
  namespace: spire-server
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spire-server-configmap-binding
  namespace: spire-server
subjects:
- kind: ServiceAccount
  name: spire-server
  namespace: spire-server
roleRef:
  kind: Role
  name: configmap-manager
  apiGroup: rbac.authorization.k8s.io
